### ISSUE TITLE
Exercise 1: Create a drop-down menu using ul and li, and styling with css.

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/css#1]
Create CSS based drop-downs menus like in given image below:Click on link to find the image:http://dl.dropbox.com/u/17934144/vtapp/exercise1.jpg

https://github.com/OkwufuluezeD/css/tree/master/Exercise1

**Comment by osifoanosike** [comment]
1. Each menu link should have a sub-menu.
2. The hover state the menu breaks its border-bottom flow, this shouldn't be. Take another close look at the diagram. You can discuss with me once.
3. The menu items shouldn't shift on hover.

**Comment by DOkwufulueze** [comment]
I've fixed it.
