### ISSUE TITLE
Exercise 2: Create a CSS layout using div(do not use tables)

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/css#2]
Create a CSS layout using div(do not use tables).Layout design is here:http://dl.dropbox.com/u/17934144/vtapp/exercise2.jpgIf you want to use background image for sidebar, here is the link for the same:http://dl.dropbox.com/u/17934144/vtapp/exercise2-bg.gif

NOTE: Widths and heights are including borders, margins, and paddings. 

https://github.com/OkwufuluezeD/css/tree/master/Exercise2

**Comment by osifoanosike** [comment]
Any need to use display:block for a div?

**Comment by DOkwufulueze** [comment]
No need since div is itself a block element. I did that in case I accidentally make the display inline. I fixed it already though.
