### ISSUE TITLE
Exercise 3: Create a CSS form layout using div's UL, LI etc

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/css#3]
Create a CSS form layout using div's UL, LI etc.Layout design is here:http://dl.dropbox.com/u/17934144/vtapp/exercise3.jpgAnd here is VinSol Logo image:http://dl.dropbox.com/u/17934144/vtapp/vinsol-logo.png

NOTE: All width and height are including borders, paddings, and margins.

https://github.com/OkwufuluezeD/css/tree/master/Exercise3

**Comment by osifoanosike** [comment]
Not sure using  `<li>` is  most ideal for the from elements. We can discuss this if in doubt.

**Comment by DOkwufulueze** [comment]
I thought same too but the question specifically requested using ul and li, so I used those.

**Comment by osifoanosike** [comment]
Ok.
